print("Starting to make a coffee")
print("Grinding coffee beans")
print("Boiling water")
print("Mixing boiled water with crushed coffee beans")
print("Pouring coffee into the cup")
print("Pouring some milk into the cup")
print("Coffee is ready!")
cups = int(input("Write how many cups of coffee you will need:"))
water = int(200)
milk = int(50)
coffee__beans = int(15)
print("For 25 cups of coffee you will need:")
print(str(cups * water) + "ml of water") 
print(str(cups * milk) + "ml of milk")
print(str(cups * coffee__beans) + "g of coffee beans")