bot_name = ("Lam4ek")
birth_year = ("2021")
print("Hello! My name is" + " " + bot_name)
print("I was created in" + " " + birth_year)
print("Please, remind me your name.")
your_name = input(str())
print("What a great name you have," + " " + your_name + "!") 